{
 "title": "Kubernetes / Views / Namespaces -15758-2",
 "description": "This is a modern 'Namespaces View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", container!=\"\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace(s) usage on total cluster CPU in %",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\"}[$__rate_interval])) / sum(machine_cpu_cores)"
      }
     ]
    },
    {
     "title": "Namespace(s) usage on total cluster RAM in %",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", image!=\"\"}) / sum(machine_memory_bytes)"
      }
     ]
    },
    {
     "title": "Kubernetes Resource Count",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})",
       "legendFormat": "Running Pods"
      },
      {
       "expr": "sum(kube_service_info{namespace=~\"$namespace\"})",
       "legendFormat": "Services"
      },
      {
       "expr": "sum(kube_ingress_info{namespace=~\"$namespace\"})",
       "legendFormat": "Ingresses"
      },
      {
       "expr": "sum(kube_deployment_labels{namespace=~\"$namespace\"})",
       "legendFormat": "Deployments"
      },
      {
       "expr": "sum(kube_statefulset_labels{namespace=~\"$namespace\"})",
       "legendFormat": "Statefulsets"
      },
      {
       "expr": "sum(kube_daemonset_labels{namespace=~\"$namespace\"})",
       "legendFormat": "Daemonsets"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_info{namespace=~\"$namespace\"})",
       "legendFormat": "Persistent Volume Claims"
      },
      {
       "expr": "sum(kube_hpa_labels{namespace=~\"$namespace\"})",
       "legendFormat": "Horizontal Pod Autoscalers"
      },
      {
       "expr": "sum(kube_configmap_info{namespace=~\"$namespace\"})",
       "legendFormat": "Configmaps"
      },
      {
       "expr": "sum(kube_secret_info{namespace=~\"$namespace\"})",
       "legendFormat": "Secrets"
      },
      {
       "expr": "sum(kube_networkpolicy_labels{namespace=~\"$namespace\"})",
       "legendFormat": "Network Policies"
      }
     ]
    },
    {
     "title": "Namespace(s) CPU Usage in cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\"}[$__rate_interval]))",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"cpu\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"cpu\"})",
       "legendFormat": "Limits"
      },
      { "expr": "sum(machine_cpu_cores)", "legendFormat": "Cluster Total" }
     ]
    },
    {
     "title": "Namespace(s) RAM Usage in bytes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", image!=\"\"})",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"memory\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"memory\"})",
       "legendFormat": "Limits"
      },
      { "expr": "sum(machine_memory_bytes)", "legendFormat": "Cluster Total" }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes Pods QoS classes",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_qos_class{namespace=~\"$namespace.*\"}) by (qos_class)",
       "legendFormat": "{{ qos_class }} pods"
      }
     ]
    },
    {
     "title": "Kubernetes Pods Err Reason",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_reason) by (reason)",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "Kubernetes Pods Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Number of container by state",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{namespace=~\"$namespace.*\",pod=~\"${pod}.*\"})",
       "legendFormat": "Ready"
      },
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\", pod=~\"${pod}.*\"})",
       "legendFormat": "Running"
      },
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace.*\"})",
       "legendFormat": "Waiting"
      },
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace.*\"}[12h]) )",
       "legendFormat": "Restarts Total"
      },
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace.*\"})",
       "legendFormat": "Terminated"
      }
     ]
    },
    {
     "title": "OOM Events by namespace, pod",
     "type": "timeseries",
     "description": "No data is generally a good thing here.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(container_oom_events_total{namespace=~\"$namespace.*\"}[$__rate_interval])) by (namespace, pod) > 0",
       "legendFormat": "namespace: {{ namespace }} - pod: {{ pod }}"
      }
     ]
    },
    {
     "title": "Container Restarts by namespace, pod",
     "type": "table",
     "description": "No data is generally a good thing here.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace.*\"}[$__range])) by (namespace, pod) > 0",
       "legendFormat": "{{ namespace }} : {{ pod }}"
      }
     ]
    },
    {
     "title": "Replicas情况",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace.*\"}) by (deployment) -  sum(kube_deployment_status_replicas_available{namespace=~\"$namespace.*\"})  by (deployment) > 0",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "多余2个容器的pod",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_info{namespace=~\"$namespace.*\", pod=~\"${pod}.*\"}) by (pod) > 2",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU usage by Pod > 0.1s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}[$__rate_interval])) by (namespace,pod,container) > 0",
     "legendFormat": "{{ pod }}_{{container}}"
    }
   ]
  },
  {
   "title": "CPU usage （Requests）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}[$__rate_interval])) by (namespace,pod,container) / avg(kube_pod_container_resource_requests{resource=\"cpu\",namespace=~\"$namespace.*\",   pod=~\"${pod}.*\"}) by (namespace,pod,container) >0",
     "legendFormat": "{{ pod }}_{{container}}"
    }
   ]
  },
  {
   "title": "CPU Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\",namespace=~\"$namespace.*\",   pod=~\"${pod}.*\"}) by (namespace,pod,container)",
     "legendFormat": "requests"
    },
    {
     "expr": " avg(kube_pod_container_resource_limits{resource=\"cpu\",namespace=~\"$namespace.*\",   pod=~\"${pod}.*\"}) by (namespace,pod,container)",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total[$__rate_interval])) by (namespace,pod,container) / sum(increase(container_cpu_cfs_periods_total{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}[$__rate_interval]))by(namespace,pod,container) * 100 > 0",
     "legendFormat": "{{pod}}_{{container}}throttle-rate"
    }
   ]
  },
  { "title": "内存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "datasource" },
  {
   "title": "内存使用%（requests）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}) by (namespace,pod,container) /sum(kube_pod_container_resource_requests{resource=\"memory\",namespace=~\"$namespace.*\",  pod=~\"${pod}.*\"}) by (namespace,pod,container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存使用%（limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}) by (namespace,pod,container) /sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=~\"$namespace.*\",  pod=~\"${pod}.*\"}) by (namespace,pod,container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by Pod > 1G",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}) by (pod) ",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "IO读写速度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}[$__rate_interval])) by (namespace,pod,container)  >0",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}_write"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}[$__rate_interval])) by (namespace,pod,container)  >0",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}_read"
    }
   ]
  },
  {
   "title": "IO读写次数（秒）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}[$__rate_interval])) by (namespace,pod,container)  >0",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}_write"
    },
    {
     "expr": "sum(irate(container_fs_reads_total{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}[$__rate_interval])) by (namespace,pod,container)  >0",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}_read"
    }
   ]
  },
  {
   "title": "网络情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true
  },
  {
   "title": "网络传输速度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}[$__rate_interval])) by (namespace,pod,container)  >0",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}_tx"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}[$__rate_interval])) by (namespace,pod,container)  >0",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}_rx"
    }
   ]
  },
  {
   "title": "网络传输丢包数(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}[$__rate_interval])) by (namespace,pod,container)  >0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}[$__rate_interval])) by (namespace,pod,container)  >0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "容器中sock数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(container_sockets{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}) by (namespace,pod,container) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "容器中线程数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(container_threads{namespace=~\"$namespace.*\", image!=\"\", pod=~\"${pod}.*\"}) by (namespace,pod,container) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistent Volumes - Capacity and usage in %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim) * 100 > 20",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    },
    {
     "title": "Persistent Volumes - Capacity and usage in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{persistentvolumeclaim}}-pvc大小"
      }
     ]
    },
    {
     "title": "Persistent Volumes - Inodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_inodes_used{namespace=~\"$namespace\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_inodes{namespace=~\"$namespace\"}) by (persistentvolumeclaim) * 100 > 20",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    }
   ]
  }
 ]
}